logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nutron?currentSchema=nutron
    username: nutron
    password: nutron
  threads:
    virtual:
      enabled: true