package org.ballz.app.service;

import org.ballz.app.domain.Ingredient;

/**
 * Service layer class for the application. Intended to encapsulate application/workflow logic that isn't strictly domain.
 * The intended flow is for the user to:
 * * in case of a new entity, the user submits a complete entity to the Service, which is stored and an ID is generated.
 * * in case of a modification of an existing entity, the user first retrieves a list of entities, selects by entityId and retrieves the complete entity,
 *   makes the required modifications, and finally submits and saves the updated entity.
 */
public class NutronService {


    public List<UUID>

    /**
     * Creates or Updates an ingredient.
     * In case of a new Ingredient, the ID field will be null and generated by the database.
     * In case of an Ingredient already containing an ID field, the intention is to replace the already existing Ingredient with the one provided.
     * @param ingredient to be stored in the database.
     */
    public void saveIngredient(Ingredient ingredient) {

    }

    public void
}
